config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  get 'timeline' => 'homes#timeline'
  get 'ranking' => 'homes#ranking'
  get 'about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'reviews/search' => 'reviews#search'
  get 'users/search' => 'users#search'

  post '/homes/guest_sign_in' => 'homes#new_guest'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show edit update destroy] do
    resource :relationships, only: %i[create destroy]
  end

  resources :movies, only: %i[index show] do
    resource :interest, only: %i[create destroy]
  end

  resources :reviews do
    resource :good, only: %i[create destroy] # /reviews/:review_id/good ①review_idをURLに持たせることでgoodのsave時などでreview_idを取得しやすいのでネストにしている。②/:good_idは不要(showページ不要)なのでresource。
    resource :bad, only: %i[create destroy] # /reviews/:review_id/bad ①review_idをURLに持たせることでbadのsave時などでreview_idを取得しやすいのでネストにしている。②/:bad_idは不要(showページ不要)なのでresource。
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @genres = GENRES

    @movie_total_pages = Tmdb::Movie.popular.total_pages
    @page = params[:page_id].to_i

    @next_page = if params[:page_id].present?
                   @page + 1
                 else
                   @page + 2
                 end

    @prev_page = if params[:page_id].to_i == 1
                   1
                 else
                   @page - 1
                 end

    if @movie_total_pages > 10
      first = [1, @page - 4].max
      @first = [first, @movie_total_pages - 9].min
      last = [10, @page + 5].max
      @last  = [last, @movie_total_pages].min
      @pages = (@first..@last).each
    else
      @pages = [*1..@last]
    end

    @popular_movie = Tmdb::Movie.popular(page: params[:page_id])
  end

  def show
    @movie = Tmdb::Movie.detail(params[:id])
    @movie_id = params[:id]
    @images = Tmdb::Movie.posters(params[:id])

    @review = Review.new
    @reviews = Review.where(movie_id: params[:id]).page(params[:page]).reverse_order
    @review_count = Review.where(movie_id: params[:id], user_id: current_user.id).count if user_signed_in?
    @user_review = Review.find_by(movie_id: params[:id], user_id: current_user.id) if user_signed_in?

    if user_signed_in?
      @interests = Interest.find_by(user_id: current_user.id, movie_id: params[:id])
    end # current_userが該当のmovieをお気に入り登録済みか確認するための検索
    @interest_users = Interest.where(movie_id: params[:id]).count if user_signed_in? # 該当のmovieをお気に入りしているuserの数を調べる
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def image_url
    @movie.poster_path
  end
end

app/views/movies/index.html.erb
<div class="movie-index-title">人気の映画 - <%= @popular_movie.total_results %> 作品</div>
<div class="genre_search mt-4 shadow-sm">
  <div class="search_heading">ジャンルで映画検索</div>
  <div class="search_items">
    <% @genres.each do |genre| %>
      <%= link_to search_path(genre_id: genre[:id]) do %>
        <div class="genre-button"><%= genre[:name] %></div>
        <% end %>
        <% end %>
  </div>
 </div>
<div class="container-fluid">
  <ul class="horizontal-list">
    <div class="movies-list">
    	<% @popular_movie.results.each do |movie| %>
    		<% if movie %>
    			<div class="movie-count-card index-cards">
              <div class="card" style="border-radius: 20px;">
               <%= link_to movie_path(movie.id) do %>
                <% if movie.poster_path %>
          				<%= image_tag('https://image.tmdb.org/t/p/w500' + movie.poster_path, class: 'movie-count-img index-cards-img') %>
          			<% else %>
          				<%= image_tag('https://dummyimage.com/500x750/000/fff', class: 'movie-count-img index-cards-img') %>
          			<% end %>
          		 <% end %>
                <div class="card-body index-cards-body" style="padding: 10px;">
                  <div class="card-title movie-title"><%= movie.title %></div>
                  <p id="index-cards-text"  class="card-text"><%= movie.release_date %></p>
                <% if user_signed_in? %>
                  <% if current_user.interests.find_by(movie_id: movie.id).present? %>
                    <div class="index-cards-bottom"><%= link_to "追加済み", movie_interest_path(movie.id), class:"btn btn-info btn-sm", method: :delete %></div>
                  <% else %>
                    <div class="index-cards-bottom"><%= link_to "観たい！", movie_interest_path(movie_id: movie.id, title: movie.title, poster_path: movie.poster_path), class:"btn btn-warning btn-sm", method: :post %></div>
                  <% end %>
                  <div class="index-review-button">
              			<% if current_user.reviews.find_by(movie_id: movie.id).present? %>
                			<%= link_to movie_path(movie.id) do %>
                			  <button type="button" class="btn btn-info btn-sm" >レビュー済み</button>
                			 <% end %>
              			<% else %>
              			  <%= link_to movie_path(movie.id) do %>
              			   <button type="button" class="btn btn-warning btn-sm" >レビューする</button>
              			  <% end %>
              			<% end %>
              		</div>
              	<% end %>
                </div>
              </div>
            </div>
    		<% end %>
    	<% end %>
    </div>
  </ul>
</div>


<div class="container  pagenation" >
  <div class="row justify-content-center">
   <% if params[:page_id].present? %>
    <%= link_to  root_path(page_id: @prev_page) do %>
      <button type="button" title="Previous 20 movies" class="page-button">
        <span class="page-button-text">Prev</span>
      </button>
   <% end %>
    <% end %>
    <% @pages.each do |page| %>
    <% if @page == page %>
      <%= link_to "#{page}", root_path(page_id: page), class: "page current_page" %>
    <% else %>
      <%= link_to "#{page}", root_path(page_id: page), class: "page" %>
    <% end %>
  <% end %>
  <%= link_to  root_path(page_id: @next_page) do %>
  <button type="button" title="Next 20 movies" class="page-button">
   <span class="page-button-text">Next</span>
  </button>
  <% end %>
  </div>
</div>

app/views/movies/show.html.erb
 <div class="container">
  <div id="alert-message">
    <% if flash[:review_alert].present? %>
		  <% flash.each do |key, message| %>
		    <div class="alert alert-danger mt-1 auto-hide  text-center">
		      <% message2 = message.gsub(",","<br>") %>
		      <%= message2.html_safe %>
		     </div>
		   <% end %>
		 <% end %>
  </div>
</div>

<section id="detail" style="background-image: url(<%= "https://image.tmdb.org/t/p/original" + "#{@movie.backdrop_path}"%>);">
	<div class="background-custom">
	<div class="movie-content">
		<div class="content-left">
			<% if @movie.poster_path %>
				<%= image_tag('https://image.tmdb.org/t/p/w500' + @movie.poster_path) %>
			<% else %>
				<%= image_tag('https://dummyimage.com/500x750/000/fff', class: 'fallback-thumbnail') %>
			<% end %>
		</div>

		<div class="content-right">
			<div class="movie-info-top">
				<div class="movie-show-title"><%= @movie.title %></div>
				<% if @movie.title != @movie.original_title %>
				<div class="movie-show-originaltitle">(<%= @movie.original_title %>)</div>
				<% end %>
					<div class="movie-info-date">
						<span class="movie-release">公開日: <%= @movie.release_date.to_date %></span>
						<span class="movie-genres"><%= @movie.genres.map(&:name).join(', ') %></span>
					</div>
			</div>
      <div class="movie-user-action">
				<% if user_signed_in? %>
					<div class="movie-follow-button">
						<% if @review_count < 1 %>
							<button type="button" class="btn btn-warning btn-sm movie-button" data-toggle="modal" data-target="#testModal">レビューする</button>
						<% else %>
					 		<%= link_to edit_review_path(@user_review) do %>
					  	<button type="button" class="btn btn-info btn-sm movie-button" >レビュー済み</button>
					 		<% end %>
					 	</div>
					<% end %>
						<div class="movie_interest movie-button" id="movie-<%= @movie_id %>_interest">
		         		<%= render 'interests/interest', movie: @movie %>
		        	</div>
			　<% else %>
			　 ログインしてレビューをする
			  <% end %>
			 </div>
        <div class="movie-overview">
        	<div class="overview-title">概要</div>
				　<div class="overview-text"><%= @movie.overview %></div>
			</div>
		</div>

	    <!-- ボタン・リンククリック後に表示される画面の内容 -->
	    <div class="modal fade" id="testModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
	       <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
	  			<div class="modal-content" style="color:black;">
			    		<%= form_with(model: @review, local: true) do |form| %>
			    		   <%= form.hidden_field :movie_id, :value => @movie.id %>
		   				   <%= form.hidden_field :title, :value => @movie.title %>
						   <%= form.hidden_field :poster_path, :value => @movie.poster_path %>
			    			<div class="modal-header">
			      			<div class="modal-title">レビューする</div>
			      			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			        			<span aria-hidden="true">&times;</span>
			      			</button>
			    			</div>
			    		<div class="modal-body">
			    		<div class="form-group" id="star">
							 <%= form.label :total_score %>
							 <%= form.hidden_field :total_score, id: :review_star %>
					    </div>
			      		<div class="form-group field">
			        		<%= form.label :本文 , class: "form-control-label"%>
			        		<%= form.text_area :body, size: "40x10", class: "form-control" %>
			      		</div>
			    		</div>
			    		<div class="modal-footer actions">
			    			<div class="custom-control custom-switch my-4 custom-control custom-radio">
			    				<div class="spoiler-box">
							      <%= form.check_box :spoiler, checked_value: "true", unchecked_value: "false", class: "custom-control-input" %>
							      <%= form.label :spoiler, class: "ml-2 custom-control-label" %>
							        <i class="fas fa-exclamation-triangle" style="margin-right:60px;">ネタバレを含んでいたらチェックをお願いします</i>
							     </div>
							     <div class="review-submit-button">
			      				<%= form.submit "書き込む", class: "btn btn-primary btn-sm"%>
			      			 </div>
			    		</div>
			    	<% end %>
			    	 <script>
			    	　 $('#star').empty();
					   $('#star').raty({
					   size: 36,
					   starOff: '<%= asset_path('star-off.png') %>',
					   starOn: '<%= asset_path('star-on.png') %>',
					   starHalf: '<%= asset_path('star-half.png') %>',
					   scoreName: 'review[total_score]',
					   half: true,
					   });
					 </script>
	  	 		</div>
			</div>
	 	</div>
	</div>
	</div>
</section>


<section id="movie-review" >


  	<div class="page-header container"><%= "「#{@movie.title}」に投稿された評価・感想"%></div>
    <% @reviews.each do |review| %>
     <div class="main posts-index">
  		<div class="container">
      <div class="posts-index-item">
        <div class="post-left">
        　<% if review.user.image_id? %>
            <img src="<%= review.user.image_id %>" >
          <% else %>
            <%= image_tag asset_path("default.jpg", alt: "ユーザー画像") %>
          <% end %>
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to("#{review.user.name}の感想・評価", "/users/#{review.user.id}") %>
          </div>
          <div class="post-time">
        		<%= review.created_at %>
      		</div>
      		<div class="post-raty">
      		 	<div id="star-rate-<%= review.id %>" class="rate-number">
		          <script>
		          $('#star-rate-<%= review.id %>').empty();
		          $('#star-rate-<%= review.id %>').raty({
		            size: 36,
		            starOff:  '<%= asset_path('star-off.png') %>',
		            starOn : '<%= asset_path('star-on.png') %>',
		            starHalf: '<%= asset_path('star-half.png') %>',
		            half: true,
		            readOnly: true,
		            score: <%= review.total_score %>,
		          });
		          </script>
          	</div>
          	<div class="rate-number"><%= review.total_score %></div>
          </div>


          <% if review.spoiler.present? %>
            <div class="hidden_box">
              <label for="label/#{review.id}">
                <i class="fas fa-exclamation-triangle">ネタバレを表示</i>
              </label>
              <input type="checkbox" id="label/#{review.id}"/>
              <div class="hidden_show">
                <%= link_to "/reviews/#{review.id}" do %>
                 <div class="review-text">
                   <%= safe_join(review.body.truncate(300).split("\n"),tag(:br)) %>
                    <% if review.body.size >= 300 %>
                      <p><<<続きを読む</p>
                    <% end %>
                 </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <%= link_to "/reviews/#{review.id}" do %>
             <div class="review-text">
               <%= safe_join(review.body.truncate(300).split("\n"),tag(:br)) %>
                <% if review.body.size >= 300 %>
                  <p><<<続きを読む</p>
                <% end %>
             </div>
            <% end %>
          <% end %>



         <div class="review_index_card_footer">
         <% if user_signed_in? %>
          <div class="review_index_good-bad" id="review-<%= review.id %>_good">
           <%= render 'goods/good-bad', review: review %>
           <% end %>
          </div>
     <% if user_signed_in? %>
      <% if review.user_id == current_user.id %>
        <div class="post-menus">
          <%= link_to("編集", "/reviews/#{review.id}/edit", {data: {toggle: "modal"}, data: {target: "#testModal"}}) %>
          <%= link_to "削除", "/reviews/#{review.id}", method: :delete, data: {confirm: '本当に削除して良いですか?',cancel: 'やめる',commit: '削除する'}, title: '削除確認' %>
        </div>
      <% end %>
      <% end %>

    </div>
        </div>
      </div>
  </div>
</div>
<% end %>
  </section>

  <script>
  $(function() {
    setTimeout("$('.auto-hide').fadeOut('slow')", 1500);
  });
</script>