config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  get 'timeline' => 'homes#timeline'
  get 'ranking' => 'homes#ranking'
  get 'about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'reviews/search' => 'reviews#search'
  get 'users/search' => 'users#search'

  post '/homes/guest_sign_in' => 'homes#new_guest'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show edit update destroy] do
    resource :relationships, only: %i[create destroy]
  end

  resources :movies, only: %i[index show] do
    resource :interest, only: %i[create destroy]
  end

  resources :reviews do
    resource :good, only: %i[create destroy] # /reviews/:review_id/good ①review_idをURLに持たせることでgoodのsave時などでreview_idを取得しやすいのでネストにしている。②/:good_idは不要(showページ不要)なのでresource。
    resource :bad, only: %i[create destroy] # /reviews/:review_id/bad ①review_idをURLに持たせることでbadのsave時などでreview_idを取得しやすいのでネストにしている。②/:bad_idは不要(showページ不要)なのでresource。
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image_id, ImageUploader

  validates :name, uniqueness: :true, length: { maximum: 20 }

  enum sex: { '--': 0, 男性: 1, 女性: 2, その他: 9 }

  has_many :goods, dependent: :destroy
  has_many :bads, dependent: :destroy

  has_many :reviews, dependent: :destroy
  has_many :good_reviews, through: :goods, source: :review # has_many a, through: :b で、bを通したuser.aが使える。aをreviewsにするとhas_many :reviewsと被ってしまう為、sourceにモデル名を書いた上でaの名前を変えている
  has_many :bad_reviews, through: :bads, source: :review # has_many a, through: :b で、bを通したuser.aが使える。aをreviewsにするとhas_many :reviewsと被ってしまう為、sourceにモデル名を書いた上でaの名前を変えている

  has_many :interests, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id # 外部キーをfollowing_idとしているので、フォローする側から見たRelasionships
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id # 外部キーをfollower_idとしているので、フォローされる側から見たRelasionships
  has_many :followers, through: :passive_relationships, source: :following

  attachment :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]

  def self.form_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def followed_by?(user)
    passive_relationships.where(following_id: user.id).exists? # exists?の方がいいかも
  end

  def timeline
    Review.where('user_id IN (?)', following_ids)
  end

  def self.follower_ranks
    User.find(Relationship.group(:follower_id).order('count(follower_id) desc').limit(5).pluck(:follower_id))
  end
  ENV['HOST']
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def twitter
    callback_for(:twitter)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.form_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except('extra')
      flash[:notice] = '登録済みメールアドレスの可能性があります'
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
    @users = @q_header.result(distinct: true) if @q_header
  end

  def show
    @user = User.find_by(id: params[:id])

    @reviews = @user.reviews.page(params[:page]).reverse_order
    @good_reviews = @user.good_reviews.page(params[:page]).reverse_order
    @bad_reviews = @user.bad_reviews.page(params[:page]).reverse_order

    @user_followings = @user.followings.page(params[:page])
    @user_followers = @user.followers.page(params[:page])

    @interests = @user.interests.page(params[:page])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      sleep(3)
      redirect_to user_path(@user), notice: 'ユーザー情報を更新しました'
    else
      render :edit
    end
  end

  def search
    @q = User.search(search_params)
    @users = @q.result(distinct: true).page(params[:page]).reverse_order
    render :index
  end

  private

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = 'このページにはアクセスできません'
      redirect_back(fallback_location: user_path(current_user))
    elsif @user.name == 'guestuser'
      redirect_to request.referer
      flash[:notice] = 'ゲストユーザーは編集機能を使用できません'
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :image_id, :email, :birthday, :sex, :intro)
  end

  def search_params
    params.require(:q).permit(:name_cont, :intro_cont, :sex_eq, :birthday_gteq, :birthday_lteq, :birthday_to_age_gteq,
                              :birthday_to_age_lteq)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def age(birthday)
    (Date.today.strftime('%Y%m%d').to_i - birthday.strftime('%Y%m%d').to_i) / 10_000
  end
end

app/views/users/_user_interest.html.erb
 <div class="container">
   <ul class="horizontal-list">
     <% interests.each do |review| %>
    	<div class="movie-count-card index-cards">
        <div class="card" style="border-radius: 20px;">
          <%= link_to movie_path(review.movie_id) do %>
            <% if review.poster_path %>
      				<%= image_tag('https://image.tmdb.org/t/p/w500' + review.poster_path, class: 'movie-count-img index-cards-img') %>
      			<% else %>
      				<%= image_tag('https://dummyimage.com/500x750/000/fff', class: 'movie-count-img index-cards-img') %>
      			<% end %>
      		 <% end %>
            <div class="card-body index-cards-body" style="padding: 10px;">
              <div class="card-title movie-title"><%= review.title %></div>
              <p id="index-cards-text"  class="card-text"><%= "追加した日: #{review.created_at}" %></p>
            <% if user_signed_in? %>
              <% if current_user.interests.find_by(movie_id: review.movie_id).present? %>
                <div class="index-cards-bottom"><%= link_to "追加済み", movie_interest_path(review.movie_id), class:"btn btn-info btn-sm", method: :delete %></div>
              <% else %>
                <div class="index-cards-bottom"><%= link_to "観たい！", movie_interest_path(movie_id: review.movie_id, title: review.title, poster_path: review.poster_path), class:"btn btn-warning btn-sm", method: :post %></div>
              <% end %>
              <div class="index-review-button">
          			<% if current_user.reviews.find_by(movie_id: review.movie_id).present? %>
            			<%= link_to movie_path(review.movie_id) do %>
            			  <button type="button" class="btn btn-info btn-sm" >レビュー済み</button>
            			 <% end %>
          			<% else %>
          			  <%= link_to movie_path(review.movie_id) do %>
          			   <button type="button" class="btn btn-warning btn-sm" >レビューする</button>
          			  <% end %>
          			<% end %>
          		</div>
          		<% end %>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
</div>

app/views/users/_user_search.html.erb
<div>
  <h5 class="user-search-heading w-100 text-center" style="padding-top: 15px;">検索条件</h5>
  <% if params[:q] %>
    <div class="search_field px-1">
      <% unless params[:q][:birthday_to_age_gteq].empty? %>
        <div class="font-weight-bold">年齢: <%= params[:q][:birthday_to_age_gteq] %> 歳以上</div>
      <% end %>
      <% unless params[:q][:birthday_to_age_lteq].empty? %>
        <div class="font-weight-bold">年齢: <%= params[:q][:birthday_to_age_lteq] %> 歳以下</div>
      <% end %>

      <% unless params[:q][:sex_eq].empty? %>
        <% if params[:q][:sex_eq] == '1' %>
          <div class="font-weight-bold">性別: 男姓</div>
        <% elsif params[:q][:sex_eq] == '2' %>
          <div class="font-weight-bold">性別: 女姓</div>
        <% else %>
          <div class="font-weight-bold">性別: その他</div>
        <% end %>
      <% end %>

      <% unless params[:q][:intro_cont].empty? %>
        <div class="font-weight-bold"> 自己紹介: <%= params[:q][:intro_cont] %> </div>
      <% end %>

      <% unless params[:q][:name_cont].empty? %>
        <div class="font-weight-bold">名前: <%= params[:q][:name_cont] %> </div>
      <% end %>
    </div>
  <% else %>
    <div class="search_field text-center">検索条件はありません</div>
  <% end %>
</div>

<h5 class="search-heading w-100">ユーザー検索</h5>
<div class="search_field px-1">
  <%= search_form_for(q, url:users_search_path) do |f| %>
    <p class="border-bottom"></p>
      <%= f.label :birthday, '年齢', class:"mr-2 font-weight-bold" %>
      <br />
        <div class="user-search-age">
          <%= f.number_field :birthday_to_age_gteq, in: 0..150, include_blank: true %>
           歳〜
          <%= f.number_field :birthday_to_age_lteq, in: 0..150, include_blank: true %>
           歳
        </div>
        <p class="border-bottom"></p>
          <%= f.label :sex_eq, '性別', class:"mr-2 font-weight-bold" %>
          <br />
          <%= f.radio_button 'sex_eq', '', {:checked => true} %>
          <%= f.label :sex_eq_, '指定なし' %>
          <%= f.radio_button 'sex_eq', '1' %>
          <%= f.label :sex_eq_1, '男姓' %>
          <%= f.radio_button 'sex_eq', '2' %>
          <%= f.label :sex_eq_2, '女姓' %>
          <%= f.radio_button 'sex_eq', '9' %>
          <%= f.label :sex_eq_9, 'その他' %>
        <p></p>
          <%= f.label :intro_cont, '自己紹介', class:"mr-2 font-weight-bold" %>
          <%= f.search_field :intro_cont %>
        <p></p>
          <%= f.label :name_cont, '名前', class:"mr-2 font-weight-bold user-search-name" %>
          <%= f.search_field :name_cont %>
        <div class="text-center mb-4">
          <%= f.submit class:"btn btn-info rounded-pill"%>
        </div>
    <% end %>
</div>

app/views/users/_users.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <div class="row justify-content-around">
    <% users.each do |user| %>
  <div class="col-sm-6">
     <div  id="card" style="width: 20rem;">

  <div class="card-body">
    <div class="card-title">

      <div class="users-index-card">
        <div class="user-left">
          <% if user.image_id? %>
            <img src="<%= user.image_id %>" >
          <% else %>
           <%= image_tag asset_path("default.jpg", alt: "ユーザー画像") %>
          <% end %>
        </div>
          <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
        </div>
    </div>
    <div class="card-text user-data-count">
      <div class="count-box">
        <span class="card-label">Followers</span>
        <span class="card-count"><%= user.passive_relationships.count %></span>
      </div>
      <div class="count-box">
        <span class="card-label">Followings</span>
        <span class="card-count"><%= user.active_relationships.count %></span>
      </div>
      <div class="follow-box">
        <% if user_signed_in? %>
        <% if user != current_user %>
          <% if user.followed_by?(current_user) %>
            <%= link_to 'フォロー中', user_relationships_path(user), class:"btn btn-info btn-sm mb-4", method: :delete, data: {confirm: 'フォローを外してもよろしいですか？',cancel: 'やめる',commit: 'フォローを外す'}, title: '確認画面' %>
          <% else %>
            <%= link_to 'フォローする', user_relationships_path(user), class:"btn btn-warning btn-sm mb-4", method: :post %>
          <% end %>
        <% end %>
        <% end %>
      </div>
      <% if user.intro.present? %>
      <%= link_to user_path(user) do %>
      <div class="user-intro">
    　  <div>
    　     <%= safe_join(user.intro.truncate(50).split("\n"),tag(:br)) %>
              <% if user.intro.size >= 50 %>
                <p>続きを読む</p>
              <% end %>
    　  </div>
    　</div>
    　<% end %>
    　<% end %>
    </div>
  </div>
</div>
</div>
<% end %>
</div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="devise_container text-center">
  <h2 class="mt-4">登録情報編集 / 退会</h2>

 <%= form_with model: @user, local: true do |f| %>
    <div class="field form-group">
      <%= f.label :name, "Name(半角英数字, 10文字まで)" %><br />
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :email, "Email" %><br />
      <%= f.email_field :email, :class => "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :birthday, "生まれ年(任意)" %>
      <%= f.label :sex, "性別(任意)" %>
    </div>


    <div class="field form-group form-inline" style="display:block;">
      <%= f.date_select :birthday, {start_year: 1940, end_year: Time.now.year - 10, date_separator: '/ ', prompt:"--" }, :class => "form-control" %>
      <%= f.select :sex, User.sexes.keys, :selected=>User.sexes[@user.sex], :class => 'form-control' %>


    </div>

    <div class="field form-group">
      <%= f.label :intro, "自己紹介(任意)" %><br />
      <%= f.text_area :intro, :class => "form-control" %>
    </div>

    <div class="field form-group has-icon">
      <div>プロフィール画像(任意)</div>
      <div class="user-edit-image">
        <div class="user-img">
         <% if @user.image_id? %>
            <%= image_tag @user.image_id.url, id: :img_prev %>
         <% else %>
            <%= image_tag asset_path("default.jpg", alt: "ユーザー画像") %>
         <% end %>
         </div>
         <div class="img-button">
          <button type="button" class="btn btn-outline-secondary rounded-pill form-control">
             <%= f.file_field :image_id, id: :user_img, accept: 'image/jpeg,image/gif,image/png' %>
          </button>
          </div>
      </div>
    </div>
    <div class="actions mx-auto row mt-5">
      <div class="col-md"></div>
      <div class="col-md"><%= f.submit "更新する", class:"btn btn-success form-control" %></div>
      <div class="col-md"></div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#user_img").change(function(){
        readURL(this);
    });
  });
</script>

app/views/users/index.html.erb
 <div class="card container shadow-sm col-sm-4 text-center" style="margin-top: 50px;">
    <%= render 'users/user_search', q: @q %>
 </div>
  <div class="container" style="margin-top: 50px;">
    <%= paginate @users %>
  </div>
    <%= render 'users/users', users: @users %>
  <div class="container">
    <%= paginate @users %>
  </div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user-show-card">
      <div class="card-body">
        <p class="card-text">
          <div class="main user-show-date">
              <div class="user">
                <div>
                  <% if @user.image_id? %>
                    <img src="<%= @user.image_id %>" >
                  <% else %>
                    <%= image_tag asset_path("default.jpg", alt: "ユーザー画像") %>
                  <% end %>
                </div>
                <div class="user-name"><%= @user.name %></div>
                 <% if @user.birthday.present? %>
                  <p class="user-old"><%= age(@user.birthday) %>歳</p>
                 <% end %>
                 <% if @user.intro.present? %>
                <p class="user-show-intro"><%= safe_join(@user.intro.split("\n"),tag(:br))%></p>
                <% end %>
                <p><%= @user.email %></p>
                <% if user_signed_in? %>
                <% if @user.id == current_user.id %>
                  <%= link_to("編集", "/users/#{@user.id}/edit") %>
                <% end %>
                <% end %>
              </div>
        <% if user_signed_in? %>
        <% if @user != current_user %>
          <% if @user.followed_by?(current_user) %>
            <%= link_to 'フォロー済み', user_relationships_path(@user), class:"btn btn-info btn-sm mb-4 text-center", method: :delete, data: {confirm: 'フォローを外してもよろしいですか？'} %>
          <% else %>
            <%= link_to 'フォローする', user_relationships_path(@user), class:"btn btn-warning btn-sm mb-4 text-center", method: :post %>
          <% end %>
        <% end %>
        <% end %>
      </p>
      </div>
    </div>
    </div>
  </div>
  </div>
    <ul class="nav nav-tabs justify-content-center text-center" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="item1-tab" data-toggle="tab" href="#item1" role="tab" aria-controls="item1" aria-selected="true">
          <div>follower</div>
          <div><%= @user.followers.count %></div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="item2-tab" data-toggle="tab" href="#item2" role="tab" aria-controls="item2" aria-selected="false">
          <div>following</div>
          <div><%= @user.followings.count %></div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="item3-tab" data-toggle="tab" href="#item3" role="tab" aria-controls="item3" aria-selected="false">
          <div>Good</div>
          <div><%= @good_reviews.count %></div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="item4-tab" data-toggle="tab" href="#item4" role="tab" aria-controls="item4" aria-selected="false">
          <div>Bad</div>
          <div><%= @bad_reviews.count %></div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="item5-tab" data-toggle="tab" href="#item5" role="tab" aria-controls="item5" aria-selected="false">
          <div>レビュー</div>
          <div><%= @reviews.count %></div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="item6-tab" data-toggle="tab" href="#item6" role="tab" aria-controls="item6" aria-selected="false">
          <div>観たいリスト</div>
          <div><%= @user.interests.count %></div>
        </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade show active" id="item1" role="tabpanel" aria-labelledby="item1-tab">
          <div class="flex user_show_container">
            <%= render 'users/users', users: @user_followers %>
          </div>
        <%= paginate @user_followers %>
      </div>
      <div class="tab-pane fade" id="item2" role="tabpanel" aria-labelledby="item2-tab">
          <div class=" user_show_container">
            <%= render 'users/users', users: @user_followings %>
          </div>
        <%= paginate @user_followings %>
      </div>
      <div class="tab-pane fade" id="item3" role="tabpanel" aria-labelledby="item3-tab">
        <%= render 'layouts/timeline', timeline_reviews: @good_reviews %>
      </div>
      <div class="tab-pane fade" id="item4" role="tabpanel" aria-labelledby="item4-tab">
        <%= render 'layouts/timeline', timeline_reviews: @bad_reviews %>
      </div>
      <div class="tab-pane fade" id="item5" role="tabpanel" aria-labelledby="item5-tab">
        <%= render 'layouts/timeline', timeline_reviews: @reviews %>
      </div>
      <div class="tab-pane fade" id="item6" role="tabpanel" aria-labelledby="item6-tab">
        <%= render 'users/user_interest', interests: @interests %>
      </div>
    </div>