config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  get 'timeline' => 'homes#timeline'
  get 'ranking' => 'homes#ranking'
  get 'about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'reviews/search' => 'reviews#search'
  get 'users/search' => 'users#search'

  post '/homes/guest_sign_in' => 'homes#new_guest'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show edit update destroy] do
    resource :relationships, only: %i[create destroy]
  end

  resources :movies, only: %i[index show] do
    resource :interest, only: %i[create destroy]
  end

  resources :reviews do
    resource :good, only: %i[create destroy] # /reviews/:review_id/good ①review_idをURLに持たせることでgoodのsave時などでreview_idを取得しやすいのでネストにしている。②/:good_idは不要(showページ不要)なのでresource。
    resource :bad, only: %i[create destroy] # /reviews/:review_id/bad ①review_idをURLに持たせることでbadのsave時などでreview_idを取得しやすいのでネストにしている。②/:bad_idは不要(showページ不要)なのでresource。
  end
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    good = current_user.goods.build(review_id: params[:review_id])
    good.save!
    bad = Bad.find_by(user_id: current_user.id, review_id: params[:review_id])
    bad.destroy if bad.present?
    @msg = 'GOODに追加しました'
  end

  def destroy
    @review = Review.find(params[:review_id])
    good = Good.find_by(user_id: current_user.id, review_id: params[:review_id])
    good.destroy!
    @msg = 'GOODから削除しました'
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_good-bad.html.erb
<p>このレビューに対する評価</p>
 <% if review.good_by?(current_user) %>
  <%= link_to review_good_path(review), class:"btn btn-light ", method: :delete, remote: true do %>
    <i class="fas fa-thumbs-up"></i>
    <%= review.goods.count %>
  <% end %>
 <% else %>
  <%= link_to review_good_path(review), class:"btn btn-light ", method: :post, remote: true do %>
    <i class="far fa-thumbs-up"></i>
    <%= review.goods.count %>
   <% end %>
  <% end %>

 <% if review.bad_by?(current_user) %>
  <%= link_to review_bad_path(review), class:"btn btn-light ", method: :delete, remote: true do %>
    <i class="fas fa-thumbs-down"></i>
    <%= review.bads.count %>
   <% end %>
 <% else %>
  <%= link_to review_bad_path(review), class:"btn btn-light ", method: :post, remote: true do %>
    <i class="far fa-thumbs-down"></i>
    <%= review.bads.count %>
   <% end %>
  <% end %>

app/views/goods/create.js.erb
$("#review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good-bad', locals: { review: @review }) %>");
$('#alert-message').html('<div class="alert alert-success mt-1 text-center auto-hide"><%= @msg %></div>');
$(function(){
    setTimeout("$('.auto-hide').fadeOut('slow')", 1500)
  });

$("#self_review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good-bad', locals: { review: @review }) %>");

app/views/goods/destroy.js.erb
$("#review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good-bad', locals: { review: @review }) %>");
$('#alert-message').html('<div class="alert alert-danger mt-1 text-center auto-hide"><%= @msg %></div>');
$(function(){
    setTimeout("$('.auto-hide').fadeOut('slow')", 1500)
  });

$("#self_review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good-bad', locals: { review: @review }) %>");