config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  get 'timeline' => 'homes#timeline'
  get 'ranking' => 'homes#ranking'
  get 'about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'reviews/search' => 'reviews#search'
  get 'users/search' => 'users#search'

  post '/homes/guest_sign_in' => 'homes#new_guest'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show edit update destroy] do
    resource :relationships, only: %i[create destroy]
  end

  resources :movies, only: %i[index show] do
    resource :interest, only: %i[create destroy]
  end

  resources :reviews do
    resource :good, only: %i[create destroy] # /reviews/:review_id/good ①review_idをURLに持たせることでgoodのsave時などでreview_idを取得しやすいのでネストにしている。②/:good_idは不要(showページ不要)なのでresource。
    resource :bad, only: %i[create destroy] # /reviews/:review_id/bad ①review_idをURLに持たせることでbadのsave時などでreview_idを取得しやすいのでネストにしている。②/:bad_idは不要(showページ不要)なのでresource。
  end
end

app/views/layouts/_error_messages.html.erb
<div class="container">
  <div id="alert-message">
    <% if object.errors.any? %>
      <% object.errors.full_messages.each do |message| %>
        <p class="alert alert-danger mt-1 auto-hide  text-center"><%= message %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer outer-block">
      <div class="logo">
        <div class="logo-title">Movie Review</div>
        </a>
      </div>
      <ul class="nav">
        <li><a href="/movies">MOVIE</a></li>
        <li><a href="/reviews">REVIEW</a></li>
        <li><a href="users">USER</a></li>
        <li><a href="/ranking">RANKING</a></li>
        <li><a href="#">CONTACT</a></li>
      </ul>
      <div class="copyright text-center">
        COPYRIGHT © MovieReview Inc. All rights Reserved.
      </div>
  </footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg " style="background: #021b30;">
    <a class="navbar-brand header-text" href="/">Movie-Review</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"><i class="fas fa-bars fa-lg"></i></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to root_path, class: 'nav-link faa-parent animated-hover header-text' do %>
             <i class="fas fa-film faa-wrench"></i>
            <span>人気の映画</span>
            <% end %>
          </li>
           <li class="nav-item">
            <%= link_to reviews_path, class: 'nav-link faa-parent animated-hover header-text' do %>
             <i class="far fa-comments faa-wrench"></i>
            <span>レビュー</span>
            <% end %>
          </li>
           <li class="nav-item">
            <%= link_to users_path, class: 'nav-link faa-parent animated-hover header-text' do %>
             <i class="fas fa-user faa-wrench"></i>
            <span>ユーザーを探す</span>
            <% end %>

          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to ranking_path, class: 'nav-link faa-parent animated-hover header-text' do %>
             <i class="fas fa-crown faa-wrench"></i>
            <span>ランキング</span>
            <% end %>
          </li>
           <li class="nav-item">
            <%= link_to timeline_path, class: 'nav-link faa-parent animated-hover header-text' do %>
             <i class="fas fa-list-ul faa-wrench"></i>
            <span>タイムライン</span>
            <% end %>
            <li class="nav-item dropdown header-text">
              <a class="nav-link dropdown-toggle header-text" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">設定</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to  "マイページ", user_path(current_user), class:"dropdown-item" %>
                <%= link_to  "プロフィール編集", edit_user_path(current_user), class:"dropdown-item" %>
                <%= link_to  "ログアウト", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link faa-parent animated-hover header-text' do %>
             <i class="fas fa-user-plus faa-wrench"></i>
            <span>登録する</span>
            <% end %>
          </li>
           <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link faa-parent animated-hover header-text' do  %>
             <i class="fas fa-sign-in-alt faa-wrench"></i>
            <span>ログイン</span>
            <% end %>
          <% end %>
          </ul>
          <% unless user_signed_in? %>
           <%= link_to 'ゲストログイン', homes_guest_sign_in_path, method: :post, class:"btn btn-success my-2 my-sm-0 guest-button" %>
          <% end %>
          <%= form_with url: search_path, class: "form-inline my-2 my-lg-0", method: :get, local: true do |f| %>
            <%= f.text_field :word, class: "form-control mr-sm-2", placeholder: '映画を探す' %>
            <%= f.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_timeline.html.erb
<% if timeline_reviews.any? %>
<div class="container">
<div class="main posts-index">

    <% timeline_reviews.each do |review| %>
      <div class="posts-index-item">
        <div class="review-main">
        <div class="review-left">
          <div class="review-user-icon">
           <% if review.user.image_id? %>
            <img src="<%= review.user.image_id %>" >
          <% else %>
            <%= image_tag asset_path("default.jpg", alt: "ユーザー画像") %>
          <% end %>
          </div>

          <div class="review-user-name">
            <%= link_to("#{review.user.name}の感想・レビュー", "/users/#{review.user.id}") %>
          </div>
          <div class="review-time">
        		<%= review.created_at %>
      		</div>
      		<div class="review-title">
            <h5><strong><%= review.title %></strong></h5>
          </div>
      			<div class="post-raty">
      		 	<div id="star-rate-<%= review.id %>" class="rate-number">
		          <script>
		          $('#star-rate-<%= review.id %>').empty();
		          $('#star-rate-<%= review.id %>').raty({
		            size: 36,
		            starOff:  '<%= asset_path('star-off.png') %>',
		            starOn : '<%= asset_path('star-on.png') %>',
		            starHalf: '<%= asset_path('star-half.png') %>',
		            half: true,
		            readOnly: true,
		            score: <%= review.total_score %>,
		          });
		          </script>
          	</div>
          	<div class="rate-number"><%= review.total_score %></div>
          </div>

          <% if review.spoiler.present? %>
            <div class="hidden_box">
              <label for="label/#{review.id}">
                <i class="fas fa-exclamation-triangle">ネタバレを表示</i>
              </label>
              <input type="checkbox" id="label/#{review.id}"/>
              <div class="hidden_show">
                <%= link_to "/reviews/#{review.id}" do %>
                 <div class="review-text">
                   <%= safe_join(review.body.truncate(300).split("\n"),tag(:br)) %>
                    <% if review.body.size >= 300 %>
                      <p><<<続きを読む</p>
                    <% end %>
                 </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <%= link_to "/reviews/#{review.id}" do %>
             <div class="review-text">
               <%= safe_join(review.body.truncate(300).split("\n"),tag(:br)) %>
                <% if review.body.size >= 300 %>
                  <p><<<続きを読む</p>
                <% end %>
             </div>
            <% end %>
          <% end %>

         </div>
         <div class="review-right">
          <div class="review-poster">
         <a href="/movies/<%= review.movie_id %>">
           <% if review.poster_path %>
				<%= image_tag('https://image.tmdb.org/t/p/w500' + review.poster_path ) %>
			<% else %>
				<%= image_tag('https://dummyimage.com/500x750/000/fff' ) %>
			<% end %>
			</a>
		  </div>


      <div class="review-button">
        <% if user_signed_in? %>
          <% if current_user.interests.find_by(movie_id: review.movie_id).present? %>
          <div class="review-cards-bottom"><%= link_to "追加済み", movie_interest_path(review.movie_id), class:"btn btn-info btn-sm", method: :delete %></div>
        <% else %>
          <div class="review-cards-bottom"><%= link_to "観たい！", movie_interest_path(movie_id: review.movie_id, title: review.title, poster_path: review.poster_path), class:"btn btn-warning btn-sm", method: :post %></div>
        <% end %>

  			<% if current_user.reviews.find_by(movie_id: review.movie_id).present? %>
    			<%= link_to movie_path(review.movie_id) do %>
    			  <button type="button" class="btn btn-info btn-sm" >レビュー済み</button>
    			 <% end %>
  			<% else %>
  			  <%= link_to movie_path(review.movie_id) do %>
  			   <button type="button" class="btn btn-warning btn-sm" >レビューする</button>
  			  <% end %>
  			<% end %>
  			<% end %>
      </div>



         </div>
         </div>

      <div class="review_index_card_footer">
        <% if user_signed_in? %>
          <div class="review_index_good-bad" id="review-<%= review.id %>_good">
           <%= render 'goods/good-bad', review: review %>
          </div>
        <% end %>
    <% if user_signed_in? %>
      <% if review.user_id == current_user.id %>
        <div class="post-menus">
          <%= link_to("編集", "/reviews/#{review.id}/edit", {data: {toggle: "modal"}, data: {target: "#testModal"}}) %>
          <%= link_to "削除", "/reviews/#{review.id}", method: :delete, data: {confirm: '本当に削除して良いですか?',cancel: 'やめる',commit: '削除する'}, title: '削除確認' %>
        </div>
      <% end %>
    <% end %>

</div>


    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
  </head>

  <body>
    <%= render 'layouts/header' %>
      <main>
        <div class="container">
          <div id="alert-message">
            <% if flash.notice.present? %>
              <p class="alert alert-success mt-1 auto-hide  text-center"><%= flash.notice %></p>
            <% if flash.alert.present? %>
              <p class="alert alert-danger mt-1 auto-hide  text-center"><%= flash.alert %></p>
          <% end %>
          <% end %>
          </div>
        </div>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>